### PR TITLE
Add 2 district address for Rep Chris Van Hollen

### PR DESCRIPTION
**Pull request by gmassanek**
I just discovered this repo after a couple frustrating nights writing my own lousy scraper. This is exactly what I need for a project!

Here's a few district addresses for Rep Van Hollen. Going to be using this on a site so might have some more updates coming. Let me know if this is the best way to submit them.

### CODE REVIEW

**Comment by jlgoldman** [comment]
Thanks so much for contributing these! This is exactly right, much appreciated.

Just curious, what's your site you'll be using these on? Just interested to know what other cool stuff people are working on.

**Comment by gmassanek** [comment]
Thanks for merging!

We are working on [My Card My Voice](http://mycardmyvoice.com/) where you can buy postage-paid postcards, pre-addressed to your legislators. We've been using the sunlight congress api but they don't have district addresses. We were going to settle on DC addresses but found out that irradiation steps delay all DC mail ~2 weeks.

The [legislator finder](http://mycardmyvoice.com/find_legislators) will take input => google geocode api => congress api (to match legislators) => your offices.csv to select the closest address to the input address for each congressman.

We're going to audit all the legislators from the recent elections to see if there are any updated addresses. We should have a PR in the next couple days.

I'm also pretty interested in state legislators eventually, so https://github.com/jlgoldman/membersofcongress/issues/4 is pretty intriguing.


### note:
We haven't launched My Card My Voice quite yet. We're hoping to soft launch by early next week (finding this data helps us out a ton), so please don't share quite yet if you're inclined to.

**Comment by jlgoldman** [comment]
Very cool! Won't share yet but looking forward to seeing this launched.

I had kind of similar thoughts in building https://www.writetogov.com/ but it never got much traction. The angle of postcards and handwritten messages is cool, very personal, I hope a lot of people use it.

Is the irradiation only for DC mail? I only learned about it after I had already launched, but it seemed like many district offices had their postal mail forwarded to the DC office anyway, so possibly even slower and still subject to irradiation unfortunately. That shouldn't stop anything, I still want piles and piles of letters and postcards filling every legislator's office, just means they can't be about time-sensitive issues.

Would consider adding the Google Places Autocomplete widget to the legislator finder for maximal ease of input (especially on mobile). In general the data is comprehensive enough that you can dispense with the geocoding API entirely because basically every US address can be selected from the autocomplete.

The cleanup after an audit would be really awesome, definitely appreciate this. I'd been waiting for the legislators from special elections to post district office data but haven't checked back on it in several weeks.

**Comment by gmassanek** [comment]
Very cool! Did you try to market writetogov anywhere? The more the better, postcards, letters, calls, etc!!

I am not sure whether district offices have irradiation policies. I've found a few congressional sites suggesting local offices are *better*, warning not to send to DC. I figure we can follow that advice and we'll see if/how many get delayed.

I'll dig into the Google Places Autocomplete widget, thanks for the suggestion!

**Comment by jlgoldman** [comment]
Yeah you're probably right and it most likely depends on the legislator - some probably prefer mail to the district office and it's handled faster, others (maybe senators) might funnel it all to DC. Will be interesting to see if you can get feedback on how long delivery takes in practice.

I did a little marketing, trying to tap into some of the desire for immediate action in November and tried to get some visibility in the new grassroots Facebook groups, on Reddit, and elsewhere. I didn't succeed into getting anybody with a big following to actively promote it which might be a key to kickstarting something. But I'm an unenthusiastic marketer so I'm optimistic you'll fare better if you're active and committed about promoting it.

**Pull request merged**
